version: 0.2

phases:
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - ECR_URI=$AWS_ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/task-manager
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin $ECR_URI
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - docker build -t task-manager:$IMAGE_TAG .
      - docker tag task-manager:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
      - docker tag task-manager:$IMAGE_TAG $ECR_URI:latest

  post_build:
    commands:
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
      - printf '[{"name":"task-manager","imageUri":"%s"}]' "$ECR_URI:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json